---
title: "Amazon Workflow Quarto"
format: html
---

```{r}
library(tidyverse)
library(tidymodels)
library(vroom)
library(glue)
library(glmnet)
library(rpart)
library(ranger)
library(embed)
```

```{r}
train_data <- vroom("train.csv") |>
  mutate(ACTION = as.factor(ACTION))
test_data <- vroom("test.csv")
```

```{r}
my_recipe <- recipe(ACTION ~ ., data=train_data) |>
  step_mutate_at(all_predictors(), fn = as.factor) |>
  step_novel(all_nominal_predictors()) |>     # EVALUATE THIS APPROACH LATER!!!
  step_other(all_nominal_predictors(), threshold = 0.002, other="Other") |> #Look at setting this back to threshold = 0.001
  step_lencode_mixed(all_nominal_predictors(), outcome = vars(ACTION)) |>
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors(), threshold=0.8) #Threshold is between 0 and 1
  
```

```{r}
my_mod <- rand_forest(mtry = tune(), min_n=tune(), trees=100) %>% #Type of model
  set_engine("ranger") %>% # What R function to use
  set_mode("classification")
```

```{r}
preg_wf <- workflow() %>%
  add_recipe(my_recipe) %>%
  add_model(my_mod)

grid_of_tuning_params <- grid_regular(mtry(range=c(1, 9)), min_n(), levels = 4)

folds <- vfold_cv(train_data, v = 5, repeats=1)
```

```{r}
CV_results <- preg_wf %>%
  tune_grid(resamples=folds,
  grid=grid_of_tuning_params,
  metrics=metric_set(accuracy, roc_auc))
```

```{r}
bestTune <- CV_results %>%
  select_best(metric="roc_auc")
```

```{r}
final_wf <- preg_wf %>%
  finalize_workflow(bestTune) %>%
  fit(data=train_data)
```


```{r}
## Predict7
tree_predictions <- final_wf %>%
  predict(new_data = test_data, type="prob")

```

```{r}
## Format the Predictions for Submission to Kaggle
kaggle_submission <- tree_predictions %>%
  bind_cols(., test_data) %>% #Bind predictions with test data
  select(id, .pred_1) %>%
  rename(ACTION=.pred_1) 

vroom_write(x=kaggle_submission, file="./Random_Forest_PCA_Predictions.csv", delim=",")
```
