---
title: "Amazon Workflow Quarto"
format: html
---

```{r}
#| include: false
library(tidymodels)
library(tidyverse)
library(vroom)
library(dplyr)
library(embed)
library(discrim)
library(naivebayes)
library(ggplot2)
```

```{r}
#| include: false
train_data <- vroom("train.csv") |>
  mutate(ACTION = factor(ACTION, levels = c("0", "1"), labels = c("No", "Yes")))
test_data <- vroom("test.csv")
```

```{r}
my_recipe <- recipe(ACTION ~ ., data=train_data) |>
  step_mutate_at(all_predictors(), fn = as.factor) |>
  step_novel(all_nominal_predictors()) |>     # EVALUATE THIS APPROACH LATER!!!
  step_other(all_nominal_predictors(), threshold = 0.002, other="Other") |> #Look at setting this back to threshold = 0.001
  step_lencode_mixed(all_nominal_predictors(), outcome = vars(ACTION)) |>
  step_range(all_numeric_predictors(), min=0, max=1) #scale to [0,1]

#prepped_recipe <- prep(my_recipe)
#train_data_2 <- bake(prepped_recipe, new_data=train_data)
#vroom_write(x=train_data_2, file="./Baked Train Data.csv", delim=",")
```

```{r}
nn_model <- mlp(hidden_units = tune(), epochs = 10) %>%
  set_engine("nnet", trace = FALSE, MaxNWts = 10000) %>% #verbose = 0 prints off less
  set_mode("classification")

my_workflow <- workflow() |>
  add_recipe(my_recipe) |>
  add_model(nn_model)
```

```{r}
## Grid of values to tune over10
tuning_grid <- grid_regular(hidden_units(range=c(1, 5)), levels = 5) # L^2 total tuning possibilities

## Split data for CV15
folds <- vfold_cv(train_data, v = 5, repeats=1)

## Run the CV18
CV_results <- my_workflow %>%
  tune_grid(resamples=folds, grid=tuning_grid, metrics=metric_set(accuracy, roc_auc))
```

```{r}
## Find Best Tuning Parameters
bestTune <- CV_results %>%
  select_best(metric = "roc_auc")

## Finalize the Workflow & fit it
final_wf <-
  my_workflow %>%
  finalize_workflow(bestTune) %>%
  fit(data=train_data)
```


```{r}
## Predict11
amazon_predictions <- final_wf %>%
  predict(new_data = test_data, type="prob")
```

```{r}
## Format the Predictions for Submission to Kaggle
kaggle_submission <- amazon_predictions %>%
  bind_cols(., test_data) %>% #Bind predictions with test data
  select(id, .pred_Yes) %>%
  rename(ACTION=.pred_Yes) 

vroom_write(x=kaggle_submission, file="./Neural_Network_Predictions_2.csv", delim=",")
```

```{r}
# Extract performance metrics
cv_metrics <- collect_metrics(CV_results)

# Filter for accuracy and plot
cv_metrics %>%
  filter(.metric == "accuracy") %>%
  ggplot(aes(x = hidden_units, y = mean)) +
  geom_line() +
  geom_point() +
  labs(
    x = "Number of Hidden Units",
    y = "Mean Accuracy (Cross-Validation)",
    title = "MLP Hyperparameter Tuning Results"
  ) +
  theme_minimal()
```



